test-sh:
	curl localhost:3000/friends -X POST -H "Content-Type: application/json" -d '{"name":"Sam","nickname":"X","occupation":"ninja"}'
con-sql:
	psql -h localhost -p 5432 -U postgres clojure_pg_example;
